version: 2
updates:

  - package-ecosystem: "npm"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[DEP]"
      prefix-development: "[DEP-DEV]"

  - package-ecosystem: "composer"
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - private-packagist
    commit-message:
      prefix: "[DEP]"
      prefix-development: "[DEP-DEV]"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[DEP]"

registries:
  private-packagist:
    type: composer-repository
    url: https://repo.packagist.com/typo3gmbh/
    username: token
    password: ${{secrets.PACKAGIST_AUTH_TOKEN}}
