framework:
  cache:
    pools:
      ip_address_pool.cache:
        adapter: cache.adapter.filesystem
      rate_limiter.cache:
        adapter: cache.adapter.filesystem

when@test:
  framework:
    cache:
      pools:
        ip_address_pool.cache:
          adapter: cache.adapter.array
        rate_limiter.cache:
          adapter: cache.adapter.array
