# A full list of configuration options can be found here:
# https://github.com/8p/EightPointsGuzzleBundle/blob/master/src/Resources/doc/configuration-reference.md
eight_points_guzzle:

    # Enable logging in prod, too. default: %kernel.debug%
    logging: true

    clients:
        bamboo:
            base_url: "https://bamboo.typo3.com/rest/api/"
            class: App\Client\BambooClient
        gerrit:
            base_url: "https://review.typo3.org/"
            class: App\Client\GerritClient
        general:
            class: App\Client\GeneralClient
        github:
            class: App\Client\GithubClient
            base_url: "https://api.github.com/"
            options:
              auth:
                - '%env(GITHUB_API_USERNAME)%'
                - '%env(GITHUB_API_PASSWORD_TOKEN)%'
              headers:
                Accept: "application/json"
        graylog:
            base_url: '%env(GRAYLOG_API)%'
            class: App\Client\GraylogClient
        rabbitManagement:
            base_url: '%env(RABBITMQ_MANAGEMENT)%'
            class: App\Client\RabbitManagementClient
        slack:
            class: App\Client\SlackClient
