magephp:
  log_dir: ./.mage/logs
  composer:
    path: composer
  exclude:
    - .ddev
    - .git
    - .gitattributes
    - .gitignore
    - .github
    - .mage
    - .vscode
    - .editorconfig
    - .env.local
    - .mage.yml
    - assets
    - var/
    - .php_cs.cache
    - .php_cs.dist
    - auth.json
    - tests
    - node_modules
    - Build
    - bin/
    - phpunit.xml.dist
    - yarn.lock
    - webpack.config.js
    - tsconfig.json
    - package.json
  environments:
    master:
      user: intercept.typo3.com
      from: ./
      host_path: /srv/vhosts/intercept.typo3.com/site/mage/
      releases: 3
      hosts:
        - srv001.typo3.com
      pre-deploy:
        - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local"}
        - composer/install: { flags: "--no-dev --optimize-autoloader"}
        - exec: { cmd: "yarn install --silent"}
        - exec: { cmd: "yarn build"}
      on-deploy:
        - exec: { cmd: "rm -Rf var/log"}
        - fs/link: { from: "../../../../shared/var/log", to: "var/log" }
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "var/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "public/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/patches", to: "var/patches" }
        - fs/link: { from: "../../../../shared/var/data.db", to: "var/data.db" }
        - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
        - fs/link: { from: "../../../../shared/var/git-core-split", to: "var/git-core-split" }
        - fs/link: { from: "../../../../shared/var/git-core-split-v8", to: "var/git-core-split-v8" }
      on-release:
      post-release:
        - exec: { cmd: "[ -d ../../../cachetool ] || mkdir -p ../../../cachetool"}
        - exec: { cmd: "[ -f ../../../cachetool/cachetool.phar ] || curl -o ../../../cachetool/cachetool.phar http://gordalina.github.io/cachetool/downloads/cachetool.phar && chmod +x ../../../cachetool/cachetool.phar"}
        - exec: { cmd: "php ../../../cachetool/cachetool.phar opcache:reset --fcgi=/var/run/intercept.typo3.com_fpm.sock --tmp-dir=/srv/vhosts/intercept.typo3.com/site/cachetool"}
        - exec: { cmd: "rm -rf var/cache"}
        - exec: { cmd: "php7.4 ./bin/console cache:warmup"}
      post-deploy:

    develop:
      user: stage.intercept.typo3.com
      from: ./
      host_path: /srv/vhosts/stage.intercept.typo3.com/site/mage/
      releases: 3
      hosts:
        - srv001.typo3.com
      pre-deploy:
        - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local"}
        - composer/install: { flags: "--no-dev --optimize-autoloader"}
        - exec: { cmd: "yarn install --silent"}
        - exec: { cmd: "yarn build"}
      on-deploy:
        - exec: { cmd: "rm -Rf var/log"}
        - fs/link: { from: "../../../../shared/var/log", to: "var/log" }
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "var/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "public/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/patches", to: "var/patches" }
        - fs/link: { from: "../../../../shared/var/data.db", to: "var/data.db" }
        - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
        - fs/link: { from: "../../../../shared/var/git-core-split", to: "var/git-core-split" }
        - fs/link: { from: "../../../../shared/var/git-core-split-v8", to: "var/git-core-split-v8" }
      on-release:
      post-release:
        - exec: { cmd: "[ -d ../../../cachetool ] || mkdir -p ../../../cachetool"}
        - exec: { cmd: "[ -f ../../../cachetool/cachetool.phar ] || curl -o ../../../cachetool/cachetool.phar http://gordalina.github.io/cachetool/downloads/cachetool.phar && chmod +x ../../../cachetool/cachetool.phar"}
        - exec: { cmd: "php ../../../cachetool/cachetool.phar opcache:reset --fcgi=/var/run/stage.intercept.typo3.com_fpm.sock --tmp-dir=/srv/vhosts/stage.intercept.typo3.com/site/cachetool"}
        - exec: { cmd: "rm -rf var/cache"}
        - exec: { cmd: "php7.4 ./bin/console cache:warmup"}
      post-deploy:
