magephp:
  log_dir: ./.mage/logs
  composer:
    path: composer
  exclude:
    - ./.ddev
    - ./.git
    - ./.gitattributes
    - ./.gitignore
    - ./.github
    - ./.mage
    - ./.vscode
    - ./.editorconfig
    - ./.env.local
    - ./.env.test
    - ./.mage.yml
    - ./assets
    - ./build
    - ./node_modules
    - ./.php_cs.cache
    - ./.php_cs.dist
    - ./auth.json
    - ./tests
    - ./phpunit.xml.dist
    - ./package.json
    - ./README.md
    - ./webpack.config.js
  environments:
    master:
      user: intercept.typo3.com
      from: ./
      host_path: /srv/vhosts/intercept.typo3.com/site/mage/
      releases: 3
      hosts:
        - shared-small.typo3.com
      pre-deploy:
        - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local"}
        - composer/install: { flags: "--no-dev --no-progress --optimize-autoloader --ansi"}
        - exec: { cmd: "npm ci"}
        - exec: { cmd: "npm run build"}
      on-deploy:
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "var/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "public/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/patches", to: "var/patches" }
        - fs/link: { from: "../../../../shared/var/data.db", to: "var/data.db" }
        - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
        - fs/link: { from: "../../../../shared/var/git-core-pr", to: "var/git-core-pr" }
      on-release:
      post-release:
        - exec: { cmd: "[ -d ../../../cachetool ] || mkdir -p ../../../cachetool"}
        - exec: { cmd: "[ -f ../../../cachetool/cachetool.phar ] || curl -L -o ../../../cachetool/cachetool.phar https://gordalina.github.io/cachetool/downloads/cachetool.phar && chmod +x ../../../cachetool/cachetool.phar"}
        - exec: { cmd: "php ../../../cachetool/cachetool.phar opcache:reset --fcgi=/var/run/intercept.typo3.com_fpm.sock --tmp-dir=/srv/vhosts/intercept.typo3.com/site/cachetool"}
        - exec: { cmd: "rm -rf var/cache"}
        - exec: { cmd: "php8.2 ./bin/console cache:warmup"}
        - exec: { cmd: "php8.2 ./bin/console app:docs-redirect-deploy"}
      post-deploy:

    develop:
      user: stage.intercept.typo3.com
      from: ./
      host_path: /srv/vhosts/stage.intercept.typo3.com/site/mage/
      releases: 3
      hosts:
        - shared-small.typo3.com
      pre-deploy:
        - exec: { cmd: "echo \"APP_ENV=prod\" >> .env.local"}
        - composer/install: { flags: "--no-dev --no-progress --optimize-autoloader --ansi"}
        - exec: { cmd: "npm ci"}
        - exec: { cmd: "npm run build"}
      on-deploy:
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "var/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/docs-build-information", to: "public/docs-build-information" }
        - fs/link: { from: "../../../../shared/var/patches", to: "var/patches" }
        - fs/link: { from: "../../../../shared/var/data.db", to: "var/data.db" }
        - fs/link: { from: "../../../shared/.env.local", to: ".env.local" }
        - fs/link: { from: "../../../../shared/var/git-core-pr", to: "var/git-core-pr" }
      on-release:
      post-release:
        - exec: { cmd: "[ -d ../../../cachetool ] || mkdir -p ../../../cachetool"}
        - exec: { cmd: "[ -f ../../../cachetool/cachetool.phar ] || curl -L -o ../../../cachetool/cachetool.phar https://gordalina.github.io/cachetool/downloads/cachetool.phar && chmod +x ../../../cachetool/cachetool.phar"}
        - exec: { cmd: "php ../../../cachetool/cachetool.phar opcache:reset --fcgi=/var/run/stage.intercept.typo3.com_fpm.sock --tmp-dir=/srv/vhosts/stage.intercept.typo3.com/site/cachetool"}
        - exec: { cmd: "rm -rf var/cache"}
        - exec: { cmd: "php8.2 ./bin/console cache:warmup"}
      post-deploy:

    legacy_hook_master:
      user: prod.docs.typo3.com
      from: ./legacy_hook/
      host_path: /srv/vhosts/prod.docs.typo3.com/site/Web/services/
      hosts:
        - prod.docs.typo3.com
      pre-deploy:
        - composer/install: { flags: "--working-dir=./legacy_hook --no-dev --no-progress --optimize-autoloader --ansi"}
      on-deploy:
      on-release:
      post-release:
      post-deploy:
