monolog:
  handlers:
    main:
      type: group
      members: [ file ]
    file:
      type: rotating_file
      level: !php/const Monolog\Logger::WARNING
      path: "%kernel.logs_dir%/%kernel.environment%.log"
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::WARNING
      hub_id: Sentry\State\HubInterface
sentry:
  register_error_listener: false
