monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: [ "!event" ]
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::WARNING
      hub_id: Sentry\State\HubInterface
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine", "!console" ]
sentry:
  register_error_listener: false
