monolog:
  handlers:
    main:
      type: group
      members: [ file ]
    file:
      type: rotating_file
      level: !php/const Monolog\Logger::ERROR
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      max_files: 10
    sentry:
      type: sentry
      level: !php/const Monolog\Logger::ERROR
      hub_id: Sentry\State\HubInterface
